Repository cloudevents/sdk-python, pull requests merged in 2022-11, with the labels that each got.

#197 feat: Kafka Protocol
  cloudevents/kafka/__init__.py
  cloudevents/kafka/conversion.py
  cloudevents/kafka/exceptions.py
  cloudevents/tests/test_kafka_conversions.py
Labels: enhancement

#201 Release/v1.7.0
  CHANGELOG.md
  cloudevents/__init__.py
  cloudevents/kafka/conversion.py
  cloudevents/tests/test_kafka_conversions.py
Labels: /release

#202 ci: refine publishing WF
  .github/workflows/pypi-release.yml
  CHANGELOG.md
Labels: enhancement

#204 hotfix: Hotfix Pydantic dependency constraints.
  .github/workflows/pypi-release.yml
  CHANGELOG.md
  cloudevents/__init__.py
  setup.py
Labels: bug
